Update test schema request JSON + remove census JSON
ONSdigital/eq-survey-runner-benchmark pull request #88
Opened 2021-05-18 12:23 UTC by MebinAbraham

### What is the context of this PR?
Removed the Census schema request JSON files and updated the existing test schema one to use the `/submit` endpoint introduced by https://github.com/ONSdigital/eq-questionnaire-runner/pull/606

### How to review 
Run the benchmark using the updated requests file against the runner branch and ensure they work as expected.

2021-05-19 07:19 UTC, berroar requested changes
The `run` command in the makefile needs to be updated as it still uses the census schema

2021-05-19 08:27 UTC, MebinAbraham commented
> The `run` command in the makefile needs to be updated as it still uses the census schema

Done

2021-05-19 08:57 UTC, berroar approved these changes

2021-05-20 09:58 UTC, JamesGardiner approved these changes

2021-05-27 13:28 UTC, merged